export { default as capitalize } from "./capitalize.js";
export { default as jwt } from "./jwt.js";
export { default as useSnackbar, snackStore } from "./use-snackbar.js";
export { default as useDocumentTitle } from "./use-document-title.js";
export { default as dayjs } from "./dayjs.js";
export { default as useLocalStorage } from "./use-local-storage.js";
export { default as isFuzzyMatch } from "./is-fuzzy-match.js";
export { default as ROUTE_PATTERNS } from "./route-patterns.js";
export { default as toBeCompressed } from "./get-to-be-compressed-extensions.js";
export const MUTATION_DELAY_IN_MS = 1000;
